### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by krisjenner** [Mrbysco/Sky_Compression#11]
[Crash report](https://paste.dimdev.org/upaduqohor.mccrash)

I think it's a conflict between SResources and JAOPCA

Using Skycompression V1.2.2.5

**Comment by Mrbysco** [comment]
The happened because I renamed the package of Sky Compression to comply with Java package naming conventions meaning every mod that adds compat needs to change their calls to the lowercase package.

JAOPCA needs to update it's Sky Compression compat
