### ISSUE TITLE
[1.12]Crash when update to the latest version

### ISSUE THREAD

**Issue by SihenZhang** [Mrbysco/Sky_Compression#2]
Minecraft Version: 1.12.2
Forge Version: 14.23.2.2619
Mod Version: 1.2.2
Singleplayer/Multiplayer: Singleplayer
Crash Report: https://paste.ee/p/ywsdH

**Comment by Mrbysco** [comment]
Fixed the issue. Uploading the new version to curse.
Sorry about that.
