### ISSUE TITLE
Extractor Recipes for Compressed Version

### ISSUE THREAD

**Issue by TwilightPSN** [Mrbysco/Sky_Compression#5]
Added a water Extractor Recipe and it doesn't seem to make the recipe automatically for the Compressed extractor. Is there something I'm doing wrong or am I supposed to added a separate script for Compressed extractor

**Comment by Mrbysco** [comment]
This is the result of keeping the previous code after taking over development of the mod. Atm you need to make recipes seperate.

I'll see what I can do about this in the future

**Comment by Mrbysco** [comment]
This github repo comes with a wiki https://github.com/Mrbysco/Sky_Compression/wiki/CraftTweaker-Support
