### ISSUE TITLE
Crash while constructing SC on the latest version

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [Mrbysco/Sky_Compression#9]
This seems... odd to me.

https://paste.dimdev.org/iminehezog.mccrash

I've gotten this crash after installing the latest version of SC, but I just checked and `hqbanana.skycompression.SkyCompression` definitely exists... I mean it's the main entry point of the mod. Did something go wrong while refactoring?

**Comment by Mrbysco** [comment]
Thing is. I was able to load the mod just fine in dev..

**Comment by Mrbysco** [comment]
Apparently there was a cache issue. As when I cleaned it and build again it DOES work now.

**Comment by Mrbysco** [comment]
Tested outside of dev

**Comment by MaxNeedsSnacks** [comment]
Yup, seems like *that* issue is gone ^^

However, the crash on load issue still isn't entirely gone, as `ne.mi.cr.CreativeTabs.setBackgroundImageName(String)` has been replaced with another method iirc, leading to this kind of crash: https://paste.dimdev.org/subipaleqo.mccrash

**Comment by MaxNeedsSnacks** [comment]
(again, interesting because you seem to be older mappings where it's still present, but for some reason it crashes with the CF provided version)

**Comment by Mrbysco** [comment]
Thought I was done :|

**Comment by Mrbysco** [comment]
https://minecraft.curseforge.com/projects/sky-compression/files/2707173

**Comment by MaxNeedsSnacks** [comment]
It's really weird because this crash actually seemed to stop occurring when I just completely wiped the gradle project, which leads me to believe that it was a caching issue, because ForgeGradle sure loves to have those

**Comment by MaxNeedsSnacks** [comment]
But yeah, now it seems to be working, thanks a ton!
